# Generated by Django 3.0.4 on 2020-03-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_auto_20200329_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='booksauthor',
            new_name='books_author',
        ),
    ]
